const fs = require('fs');
const path = require('path');

const sapConnectSnippet = [
    'Dim SapGuiAuto, application, connection, session',
    'On Error Resume Next',
    'Set SapGuiAuto = GetObject("SAPGUI")',
    'If Err.Number <> 0 Or SapGuiAuto Is Nothing Then',
    '    WScript.Echo "ERROR_NO_SAPGUI: SAP Logon is not running. Please launch SAP Logon first."',
    '    WScript.Quit 1',
    'End If',
    '',
    'Set application = SapGuiAuto.GetScriptingEngine',
    'If Err.Number <> 0 Or application Is Nothing Then',
    '    WScript.Echo "ERROR_NO_SCRIPTING: SAP GUI Scripting is disabled. Please enable scripting in SAP options."',
    '    WScript.Quit 2',
    'End If',
    '',
    'If application.Children.Count = 0 Then',
    '    WScript.Echo "ERROR_NO_CONNECTION: No active SAP connection. Please log in to your SAP system."',
    '    WScript.Quit 3',
    'End If',
    '',
    'Set connection = application.Children(0)',
    'If connection.Children.Count = 0 Then',
    '    WScript.Echo "ERROR_NO_SESSION: No open SAP session window found."',
    '    WScript.Quit 4',
    'End If',
    '',
    'Set session = connection.Children(0)',
    'If IsObject(WScript) Then',
    '    WScript.ConnectObject session,     "on"',
    '    WScript.ConnectObject application, "on"',
    'End If',
    'On Error GoTo 0',
    '',
    'On Error Resume Next',
    'session.findById("wnd[0]").maximize',
    'On Error GoTo 0'
].join('\r\n');

const handleExportPopupsSnippet = [
    'Sub HandleExportPopups()',
    '    Dim loopCount, wnd',
    '    For loopCount = 1 To 25',
    '        WScript.Sleep 1000',
    '        On Error Resume Next',
    '        Err.Clear',
    '        Set wnd = session.findById("wnd[1]")',
    '        If Err.Number = 0 And Not wnd Is Nothing Then',
    '            Err.Clear',
    '            wnd.findById("tbar[0]/btn[11]").press',
    '            If Err.Number <> 0 Then',
    '                Err.Clear',
    '                wnd.findById("tbar[0]/btn[8]").press',
    '                If Err.Number <> 0 Then',
    '                    Err.Clear',
    '                    wnd.findById("tbar[0]/btn[0]").press',
    '                End If',
    '            End If',
    '        Else',
    '            If loopCount >= 3 Then',
    '                On Error GoTo 0',
    '                Exit Sub',
    '            End If',
    '        End If',
    '        On Error GoTo 0',
    '    Next',
    'End Sub'
].join('\r\n');

const zppm6680Lines = [
    'Option Explicit',
    sapConnectSnippet,
    '',
    'Dim plant, startMonth, endMonth',
    'plant = "1840"',
    'startMonth = "2026.08"',
    'endMonth = "2027.01"',
    '',
    'If WScript.Arguments.Count >= 1 Then plant = Trim(WScript.Arguments(0))',
    'If WScript.Arguments.Count >= 2 Then startMonth = Trim(WScript.Arguments(1))',
    'If WScript.Arguments.Count >= 3 Then endMonth = Trim(WScript.Arguments(2))',
    '',
    'session.findById("wnd[0]/tbar[0]/okcd").text = "/nZPPM6680"',
    'session.findById("wnd[0]").sendVKey 0',
    '',
    'session.findById("wnd[0]/usr/ctxtPA_WERKS").text = plant',
    'session.findById("wnd[0]/usr/txtSO_EMONU-LOW").text = startMonth',
    'session.findById("wnd[0]/usr/txtSO_EMONU-HIGH").text = endMonth',
    'On Error Resume Next',
    'session.findById("wnd[0]/usr/ctxtSO_VERID-LOW").text = ""',
    'session.findById("wnd[0]/usr/ctxtSO_VERID-HIGH").text = ""',
    'session.findById("wnd[0]/usr/ctxtSO_MATNR-LOW").text = ""',
    'session.findById("wnd[0]/usr/ctxtSO_MATNR-HIGH").text = ""',
    'On Error GoTo 0',
    'session.findById("wnd[0]").sendVKey 8',
    '',
    'Dim grid, retry',
    'Set grid = Nothing',
    'For retry = 1 To 30',
    '    Err.Clear',
    '    On Error Resume Next',
    '    Set grid = session.findById("wnd[0]/usr/cntlCC_CONTAINER_0100/shellcont/shell/shellcont/shell")',
    '    If Err.Number = 0 And Not grid Is Nothing Then',
    '        On Error GoTo 0',
    '        Exit For',
    '    End If',
    '    WScript.Sleep 1000',
    'Next',
    'On Error GoTo 0',
    'If grid Is Nothing Then',
    '    WScript.Echo "ERROR_NO_GRID: ZPPM6680 ALV Grid did not load within 30 seconds."',
    '    WScript.Quit 5',
    'End If',
    '',
    'If grid.rowCount = 0 Then',
    '    WScript.Echo "ERROR_ZERO_ROWS: ZPPM6680 Plant " & plant & " (" & startMonth & " ~ " & endMonth & ") has 0 planned orders."',
    '    WScript.Quit 6',
    'End If',
    '',
    'grid.currentCellRow = 1',
    'grid.contextMenu',
    'grid.selectContextMenuItem "&XXL"',
    '',
    'HandleExportPopups',
    '',
    'WScript.Echo "SUCCESS: ZPPM6680 completed for Plant " & plant',
    'WScript.Quit 0',
    '',
    handleExportPopupsSnippet
].join('\r\n');

const zppr6470Lines = [
    'Option Explicit',
    sapConnectSnippet,
    '',
    'Dim plant, beskz, sobsl, layoutRow, wareCtrl',
    'plant = "1840"',
    'beskz = "e"',
    'sobsl = ""',
    'layoutRow = 18',
    'wareCtrl = ""',
    '',
    'If WScript.Arguments.Count >= 1 Then plant = Trim(WScript.Arguments(0))',
    'If WScript.Arguments.Count >= 2 Then beskz = Trim(WScript.Arguments(1))',
    'If WScript.Arguments.Count >= 3 Then sobsl = Trim(WScript.Arguments(2))',
    'If WScript.Arguments.Count >= 4 Then layoutRow = Trim(WScript.Arguments(3))',
    'If WScript.Arguments.Count >= 5 Then wareCtrl = Trim(WScript.Arguments(4))',
    '',
    'session.findById("wnd[0]/tbar[0]/okcd").text = "/nZPPR6470"',
    'session.findById("wnd[0]").sendVKey 0',
    '',
    'session.findById("wnd[0]/usr/btn%_SO_VBELN_%_APP_%-VALU_PUSH").press',
    'session.findById("wnd[1]/tbar[0]/btn[24]").press',
    'session.findById("wnd[1]/tbar[0]/btn[8]").press',
    '',
    'If plant <> "" Then',
    '    session.findById("wnd[0]/usr/ctxtSO_WERKS-LOW").text = plant',
    'Else',
    '    session.findById("wnd[0]/usr/ctxtSO_WERKS-LOW").text = ""',
    'End If',
    '',
    'If beskz <> "" Then',
    '    session.findById("wnd[0]/usr/ctxtSO_BESKZ-LOW").text = beskz',
    'Else',
    '    session.findById("wnd[0]/usr/ctxtSO_BESKZ-LOW").text = ""',
    'End If',
    '',
    'If sobsl <> "" Then',
    '    session.findById("wnd[0]/usr/ctxtSO_SOBSL-LOW").text = sobsl',
    'Else',
    '    session.findById("wnd[0]/usr/ctxtSO_SOBSL-LOW").text = ""',
    'End If',
    '',
    '\' Warehouse Controller (SO_WARE)',
    'If InStr(wareCtrl, ",") > 0 Then',
    '    Dim arrWare, wLow, wHigh',
    '    arrWare = Split(wareCtrl, ",")',
    '    wLow = Trim(arrWare(0))',
    '    wHigh = Trim(arrWare(UBound(arrWare)))',
    '    ',
    '    \' Method 1: If exactly 2 sequential values (like PY, PZ), set LOW and HIGH directly',
    '    If UBound(arrWare) = 1 And wLow = "PY" And wHigh = "PZ" Then',
    '        On Error Resume Next',
    '        session.findById("wnd[0]/usr/ctxtSO_WARE-LOW").text = wLow',
    '        session.findById("wnd[0]/usr/ctxtSO_WARE-HIGH").text = wHigh',
    '        If Err.Number <> 0 Then',
    '            Err.Clear',
    '            session.findById("wnd[0]/usr/txtSO_WARE-LOW").text = wLow',
    '            session.findById("wnd[0]/usr/txtSO_WARE-HIGH").text = wHigh',
    '        End If',
    '        On Error GoTo 0',
    '    Else',
    '        Dim wIdx, clipTxt',
    '        clipTxt = ""',
    '        For wIdx = 0 To UBound(arrWare)',
    '            If Trim(arrWare(wIdx)) <> "" Then',
    '                If clipTxt <> "" Then clipTxt = clipTxt & vbCrLf',
    '                clipTxt = clipTxt & Trim(arrWare(wIdx))',
    '            End If',
    '        Next',
    '        SetClipboard clipTxt',
    '        WScript.Sleep 300',
    '        On Error Resume Next',
    '        session.findById("wnd[0]/usr/btn%_SO_WARE_%_APP_%-VALU_PUSH").press',
    '        WScript.Sleep 500',
    '        session.findById("wnd[1]/tbar[0]/btn[24]").press',
    '        WScript.Sleep 300',
    '        session.findById("wnd[1]/tbar[0]/btn[8]").press',
    '        On Error GoTo 0',
    '    End If',
    'ElseIf wareCtrl <> "" Then',
    '    On Error Resume Next',
    '    session.findById("wnd[0]/usr/ctxtSO_WARE-LOW").text = wareCtrl',
    '    session.findById("wnd[0]/usr/ctxtSO_WARE-HIGH").text = ""',
    '    If Err.Number <> 0 Then',
    '        Err.Clear',
    '        session.findById("wnd[0]/usr/txtSO_WARE-LOW").text = wareCtrl',
    '        session.findById("wnd[0]/usr/txtSO_WARE-HIGH").text = ""',
    '    End If',
    '    On Error GoTo 0',
    'Else',
    '    On Error Resume Next',
    '    session.findById("wnd[0]/usr/ctxtSO_WARE-LOW").text = ""',
    '    session.findById("wnd[0]/usr/ctxtSO_WARE-HIGH").text = ""',
    '    session.findById("wnd[0]/usr/txtSO_WARE-LOW").text = ""',
    '    session.findById("wnd[0]/usr/txtSO_WARE-HIGH").text = ""',
    '    On Error GoTo 0',
    'End If',
    '',
    'session.findById("wnd[0]").sendVKey 8',
    '',
    'Dim conShell, retryCon',
    'Set conShell = Nothing',
    'For retryCon = 1 To 30',
    '    Err.Clear',
    '    On Error Resume Next',
    '    Set conShell = session.findById("wnd[0]/usr/cntlCON_S100/shellcont/shell")',
    '    If Err.Number = 0 And Not conShell Is Nothing Then',
    '        On Error GoTo 0',
    '        Exit For',
    '    End If',
    '    WScript.Sleep 1000',
    'Next',
    'On Error GoTo 0',
    'If conShell Is Nothing Then',
    '    WScript.Echo "ERROR_NO_GRID: ZPPR6470 Grid container did not load within 30 seconds."',
    '    WScript.Quit 5',
    'End If',
    '',
    'conShell.pressToolbarButton "&MB_VARIANT"',
    'session.findById("wnd[1]/usr/ssubD0500_SUBSCREEN:SAPLSLVC_DIALOG:0501/cntlG51_CONTAINER/shellcont/shell").setCurrentCell CInt(layoutRow), "TEXT"',
    'session.findById("wnd[1]/usr/ssubD0500_SUBSCREEN:SAPLSLVC_DIALOG:0501/cntlG51_CONTAINER/shellcont/shell").selectedRows = CStr(layoutRow)',
    'session.findById("wnd[1]/usr/ssubD0500_SUBSCREEN:SAPLSLVC_DIALOG:0501/cntlG51_CONTAINER/shellcont/shell").clickCurrentCell',
    '',
    'If conShell.rowCount = 0 Then',
    '    WScript.Echo "ERROR_ZERO_ROWS: ZPPR6470 Plant " & plant & " has 0 component requirement rows."',
    '    WScript.Quit 6',
    'End If',
    '',
    'conShell.currentCellRow = 1',
    'conShell.contextMenu',
    'conShell.selectContextMenuItem "&XXL"',
    '',
    'HandleExportPopups',
    '',
    'WScript.Echo "SUCCESS: ZPPR6470 completed for Plant " & plant',
    'WScript.Quit 0',
    '',
    handleExportPopupsSnippet,
    '',
    'Sub SetClipboard(txt)',
    '    Dim oExec',
    '    On Error Resume Next',
    '    Set oExec = CreateObject("WScript.Shell").Exec("clip")',
    '    If Err.Number = 0 Then',
    '        oExec.StdIn.Write txt',
    '        oExec.StdIn.Close',
    '        WScript.Sleep 200',
    '    End If',
    '    On Error GoTo 0',
    'End Sub'
].join('\r\n');

const returnHomeLines = [
    'Option Explicit',
    sapConnectSnippet,
    '',
    'Dim dRetry',
    'For dRetry = 1 To 3',
    '    On Error Resume Next',
    '    session.findById("wnd[1]/tbar[0]/btn[12]").press',
    '    session.findById("wnd[1]/tbar[0]/btn[0]").press',
    '    On Error GoTo 0',
    'Next',
    '',
    'session.findById("wnd[0]/tbar[0]/okcd").text = "/n"',
    'session.findById("wnd[0]").sendVKey 0',
    'WScript.Echo "SUCCESS: Returned to SAP Home"',
    'WScript.Quit 0'
].join('\r\n');

const outDir = path.resolve(__dirname);
fs.writeFileSync(path.join(outDir, 'zppm6680.vbs'), zppm6680Lines, 'ascii');
fs.writeFileSync(path.join(outDir, 'zppr6470.vbs'), zppr6470Lines, 'ascii');
fs.writeFileSync(path.join(outDir, 'return_home.vbs'), returnHomeLines, 'ascii');

console.log('Generated clean ASCII VBScript files without BOM in ' + outDir);
