const fs = require('fs');
const path = require('path');

const sapConnectSnippet = [
    'Dim SapGuiAuto, application, connection, session',
    'On Error Resume Next',
    'Set SapGuiAuto = GetObject("SAPGUI")',
    'If Err.Number <> 0 Or SapGuiAuto Is Nothing Then',
    '    WScript.Echo "ERROR_NO_SAPGUI: SAP Logon is not running. Please launch SAP Logon first."',
    '    WScript.Quit 1',
    'End If',
    '',
    'Set application = SapGuiAuto.GetScriptingEngine',
    'If Err.Number <> 0 Or application Is Nothing Then',
    '    WScript.Echo "ERROR_NO_SCRIPTING: SAP GUI Scripting is disabled. Please enable scripting in SAP options."',
    '    WScript.Quit 2',
    'End If',
    '',
    'If application.Children.Count = 0 Then',
    '    WScript.Echo "ERROR_NO_CONNECTION: No active SAP connection. Please log in to your SAP system."',
    '    WScript.Quit 3',
    'End If',
    '',
    'Set connection = application.Children(0)',
    'If connection.Children.Count = 0 Then',
    '    WScript.Echo "ERROR_NO_SESSION: No open SAP session window found."',
    '    WScript.Quit 4',
    'End If',
    '',
    'Set session = connection.Children(0)',
    'If IsObject(WScript) Then',
    '    WScript.ConnectObject session,     "on"',
    '    WScript.ConnectObject application, "on"',
    'End If',
    'On Error GoTo 0'
].join('\r\n');

const zppm6680Lines = [
    'Option Explicit',
    sapConnectSnippet,
    '',
    'Dim plant, startMonth, endMonth',
    'plant = "1840"',
    'startMonth = "2026.08"',
    'endMonth = "2027.01"',
    '',
    'If WScript.Arguments.Count >= 1 Then plant = Trim(WScript.Arguments(0))',
    'If WScript.Arguments.Count >= 2 Then startMonth = Trim(WScript.Arguments(1))',
    'If WScript.Arguments.Count >= 3 Then endMonth = Trim(WScript.Arguments(2))',
    '',
    'session.findById("wnd[0]/tbar[0]/okcd").text = "/nZPPM6680"',
    'session.findById("wnd[0]").sendVKey 0',
    '',
    'session.findById("wnd[0]/usr/ctxtPA_WERKS").text = plant',
    'session.findById("wnd[0]/usr/txtSO_EMONU-LOW").text = startMonth',
    'session.findById("wnd[0]/usr/txtSO_EMONU-HIGH").text = endMonth',
    'session.findById("wnd[0]").sendVKey 8',
    '',
    'session.findById("wnd[0]/usr/cntlCC_CONTAINER_0100/shellcont/shell/shellcont/shell").currentCellRow = 1',
    'session.findById("wnd[0]/usr/cntlCC_CONTAINER_0100/shellcont/shell/shellcont/shell").contextMenu',
    'session.findById("wnd[0]/usr/cntlCC_CONTAINER_0100/shellcont/shell/shellcont/shell").selectContextMenuItem "&XXL"',
    '',
    'session.findById("wnd[1]/tbar[0]/btn[8]").press',
    'On Error Resume Next',
    'session.findById("wnd[1]/tbar[0]/btn[0]").press',
    'session.findById("wnd[1]/tbar[0]/btn[11]").press',
    'On Error GoTo 0',
    '',
    'WScript.Echo "SUCCESS: ZPPM6680 completed for Plant " & plant',
    'WScript.Quit 0'
].join('\r\n');

const zppr6470Lines = [
    'Option Explicit',
    sapConnectSnippet,
    '',
    'Dim plant, beskz, sobsl, layoutRow',
    'plant = "1840"',
    'beskz = "e"',
    'sobsl = ""',
    'layoutRow = 18',
    '',
    'If WScript.Arguments.Count >= 1 Then plant = Trim(WScript.Arguments(0))',
    'If WScript.Arguments.Count >= 2 Then beskz = Trim(WScript.Arguments(1))',
    'If WScript.Arguments.Count >= 3 Then sobsl = Trim(WScript.Arguments(2))',
    'If WScript.Arguments.Count >= 4 Then layoutRow = Trim(WScript.Arguments(3))',
    '',
    'session.findById("wnd[0]/tbar[0]/okcd").text = "/nZPPR6470"',
    'session.findById("wnd[0]").sendVKey 0',
    '',
    'session.findById("wnd[0]/usr/btn%_SO_VBELN_%_APP_%-VALU_PUSH").press',
    'session.findById("wnd[1]/tbar[0]/btn[24]").press',
    'session.findById("wnd[1]/tbar[0]/btn[8]").press',
    '',
    'If plant <> "" Then',
    '    session.findById("wnd[0]/usr/ctxtSO_WERKS-LOW").text = plant',
    'Else',
    '    session.findById("wnd[0]/usr/ctxtSO_WERKS-LOW").text = ""',
    'End If',
    '',
    'If beskz <> "" Then',
    '    session.findById("wnd[0]/usr/ctxtSO_BESKZ-LOW").text = beskz',
    'Else',
    '    session.findById("wnd[0]/usr/ctxtSO_BESKZ-LOW").text = ""',
    'End If',
    '',
    'If sobsl <> "" Then',
    '    session.findById("wnd[0]/usr/ctxtSO_SOBSL-LOW").text = sobsl',
    'Else',
    '    session.findById("wnd[0]/usr/ctxtSO_SOBSL-LOW").text = ""',
    'End If',
    '',
    'session.findById("wnd[0]").sendVKey 8',
    '',
    'session.findById("wnd[0]/usr/cntlCON_S100/shellcont/shell").pressToolbarButton "&MB_VARIANT"',
    'session.findById("wnd[1]/usr/ssubD0500_SUBSCREEN:SAPLSLVC_DIALOG:0501/cntlG51_CONTAINER/shellcont/shell").setCurrentCell CInt(layoutRow), "TEXT"',
    'session.findById("wnd[1]/usr/ssubD0500_SUBSCREEN:SAPLSLVC_DIALOG:0501/cntlG51_CONTAINER/shellcont/shell").selectedRows = CStr(layoutRow)',
    'session.findById("wnd[1]/usr/ssubD0500_SUBSCREEN:SAPLSLVC_DIALOG:0501/cntlG51_CONTAINER/shellcont/shell").clickCurrentCell',
    '',
    'session.findById("wnd[0]/usr/cntlCON_S100/shellcont/shell").currentCellRow = 1',
    'session.findById("wnd[0]/usr/cntlCON_S100/shellcont/shell").contextMenu',
    'session.findById("wnd[0]/usr/cntlCON_S100/shellcont/shell").selectContextMenuItem "&XXL"',
    '',
    'session.findById("wnd[1]/tbar[0]/btn[8]").press',
    'On Error Resume Next',
    'session.findById("wnd[1]/tbar[0]/btn[11]").press',
    'session.findById("wnd[1]/tbar[0]/btn[0]").press',
    'session.findById("wnd[1]/tbar[0]/btn[11]").press',
    'On Error GoTo 0',
    '',
    'WScript.Echo "SUCCESS: ZPPR6470 completed for Plant " & plant',
    'WScript.Quit 0'
].join('\r\n');

const returnHomeLines = [
    'Option Explicit',
    sapConnectSnippet,
    '',
    'session.findById("wnd[0]/tbar[0]/okcd").text = "/n"',
    'session.findById("wnd[0]").sendVKey 0',
    'WScript.Echo "SUCCESS: Returned to SAP Home"',
    'WScript.Quit 0'
].join('\r\n');

const outDir = path.resolve(__dirname);
fs.writeFileSync(path.join(outDir, 'zppm6680.vbs'), zppm6680Lines, 'ascii');
fs.writeFileSync(path.join(outDir, 'zppr6470.vbs'), zppr6470Lines, 'ascii');
fs.writeFileSync(path.join(outDir, 'return_home.vbs'), returnHomeLines, 'ascii');

console.log('Generated clean ASCII VBScript files without BOM in ' + outDir);
